#!/usr/bin/env bash
# Generate local-only infrastructure secrets (idempotent, never committed).
#
# Creates backend/.infra.env holding the Postgres password, and keeps the
# DATABASE_URL in backend/.env pointing at the same password. Re-running never
# rotates a healthy password. A known shared default is rotated instead of
# carried forward, and a local DATABASE_URL that no longer matches is rewritten
# so the app and the database cannot drift apart silently.
set -euo pipefail

backend_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
infra_env="$backend_dir/.infra.env"
app_env="$backend_dir/.env"

# Passwords that ship in public documentation: never reused for a local install.
shared_defaults="papermind papermind_test postgres password"

# DATABASE_URL shape: postgresql+psycopg://user:password@host:port/db
url_password() {
  printf '%s' "$1" | sed -n 's#.*://[^:/]*:\([^@]*\)@.*#\1#p' || true
}

url_is_local() {
  case "$1" in
    *://*@localhost:* | *://*@127.0.0.1:*) return 0 ;;
    *) return 1 ;;
  esac
}

is_shared_default() {
  local candidate="$1" known
  for known in $shared_defaults; do
    [ "$candidate" = "$known" ] && return 0
  done
  return 1
}

read_env_value() {
  grep -E "^$2=" "$1" | cut -d= -f2- | tail -n 1 || true
}

existing_url=""
if [ -f "$app_env" ]; then
  existing_url=$(read_env_value "$app_env" DATABASE_URL)
fi
existing_password=$(url_password "$existing_url")

if [ ! -f "$infra_env" ]; then
  if [ -n "$existing_password" ] && ! is_shared_default "$existing_password"; then
    password="$existing_password"
    echo "Created $infra_env reusing the password already in $app_env."
  else
    password=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    if [ -n "$existing_password" ]; then
      echo "Created $infra_env with a random password: the previous one was a"
      echo "documented default ('$existing_password') shared by every clone."
      echo "An existing database volume still holds the old password, so either"
      echo "reset it once (docker compose -f backend/compose.yaml down -v) or run"
      echo "  ALTER USER papermind WITH PASSWORD '<new password>';"
    else
      echo "Created $infra_env with a random Postgres password."
    fi
  fi
  {
    echo "# Generated by backend/scripts/bootstrap-local.sh — local only, do not commit."
    echo "POSTGRES_USER=papermind"
    echo "POSTGRES_PASSWORD=$password"
    echo "QDRANT_API_KEY="
  } > "$infra_env"
  chmod 600 "$infra_env"
else
  echo "Keeping existing $infra_env."
fi

# Read the password back (without sourcing secrets into the shell history).
pg_password=$(read_env_value "$infra_env" POSTGRES_PASSWORD)
pg_user=$(read_env_value "$infra_env" POSTGRES_USER)
pg_user=${pg_user:-papermind}

if [ -z "${pg_password:-}" ] || [ "$pg_password" = "replace-me-run-bootstrap-local-sh" ]; then
  echo "ERROR: $infra_env has no real POSTGRES_PASSWORD." >&2
  exit 1
fi

expected_url="postgresql+psycopg://${pg_user}:${pg_password}@localhost:5432/papermind"

if [ ! -f "$app_env" ]; then
  printf 'DATABASE_URL=%s\n' "$expected_url" > "$app_env"
  echo "Created $app_env with a matching DATABASE_URL."
elif [ -z "$existing_url" ]; then
  printf '\nDATABASE_URL=%s\n' "$expected_url" >> "$app_env"
  echo "Added DATABASE_URL to $app_env."
elif [ "$existing_url" != "$expected_url" ]; then
  if url_is_local "$existing_url"; then
    # A local URL drifting from the generated password would fail to
    # authenticate; the generated password is the source of truth.
    python3 - "$app_env" "$expected_url" <<'PY'
import pathlib
import re
import sys

path, url = pathlib.Path(sys.argv[1]), sys.argv[2]
text = path.read_text()
path.write_text(re.sub(r"(?m)^DATABASE_URL=.*$", f"DATABASE_URL={url}", text))
PY
    echo "Updated DATABASE_URL in $app_env to match $infra_env."
  else
    echo "WARNING: $app_env points DATABASE_URL at a non-localhost database, so it"
    echo "         was left alone. Make sure its password matches $infra_env, or"
    echo "         drop the variable to use the local one."
  fi
fi
